baseline:
- - -1
  - -0.2
baseline_method: decibel
electrodes: '14'
epoch: default
epoch_choice: auditory_onset
epoch_choice__trial_ends: 2
epoch_choice__trial_starts: -1
intervals:
- - -1.0
  - 2.0
loaded_electrodes: 13-16,24
project_name: devel
reference: default
reference_name: default
save_pipeline: yes
subject_code: YAB
type: power
