vertical_spacing: ~
subject_code: DemoSubject
pwelch_params:
  window_size: 4000
  noverlap: 2000.0
pwelch_frequency_limit:
- 0
- 300
project_name: demo
loaded_electrodes: 13-16,24
highlight_electrodes: ''
hide_electrodes: ''
filter_notch:
  enabled: no
filter_bandpass:
  enabled: no
block: 008
analysis_time: ~
analysis_electrodes: 13-16,24
analysis_block: 008
