kernel_table:
  Frequency:
  - 2
  - 22
  - 42
  - 62
  - 82
  - 102
  - 122
  - 142
  - 162
  - 182
  Cycles:
  - 3.0
  - 8.0
  - 11.0
  - 12.0
  - 14.0
  - 15.0
  - 16.0
  - 17.0
  - 18.0
  - 19.0
pre_downsample: 4.0
precision: float
project_name: test
subject_code: PAV006
target_sample_rate: 100.0
