target_sample_rate: 100.0
subject_code: PAV020
project_name: YAEL
precision: float
pre_downsample: 4.0
kernel_table:
  Frequency:
  - 2
  - 4
  - 6
  - 8
  - 10
  - 12
  - 14
  - 16
  - 18
  - 20
  - 22
  - 24
  - 26
  - 28
  - 30
  - 32
  - 34
  - 36
  - 38
  - 40
  - 42
  - 44
  - 46
  - 48
  - 50
  - 52
  - 54
  - 56
  - 58
  - 60
  - 62
  - 64
  - 66
  - 68
  - 70
  - 72
  - 74
  - 76
  - 78
  - 80
  - 82
  - 84
  - 86
  - 88
  - 90
  - 92
  - 94
  - 96
  - 98
  - 100
  - 102
  - 104
  - 106
  - 108
  - 110
  - 112
  - 114
  - 116
  - 118
  - 120
  - 122
  - 124
  - 126
  - 128
  - 130
  - 132
  - 134
  - 136
  - 138
  - 140
  - 142
  - 144
  - 146
  - 148
  - 150
  - 152
  - 154
  - 156
  - 158
  - 160
  - 162
  - 164
  - 166
  - 168
  - 170
  - 172
  - 174
  - 176
  - 178
  - 180
  - 182
  - 184
  - 186
  - 188
  - 190
  - 192
  - 194
  - 196
  - 198
  - 200
  Cycles:
  - 3.0
  - 4.0
  - 5.0
  - 5.0
  - 6.0
  - 6.0
  - 7.0
  - 7.0
  - 7.0
  - 8.0
  - 8.0
  - 8.0
  - 9.0
  - 9.0
  - 9.0
  - 9.0
  - 10.0
  - 10.0
  - 10.0
  - 10.0
  - 11.0
  - 11.0
  - 11.0
  - 11.0
  - 11.0
  - 11.0
  - 12.0
  - 12.0
  - 12.0
  - 12.0
  - 12.0
  - 13.0
  - 13.0
  - 13.0
  - 13.0
  - 13.0
  - 13.0
  - 13.0
  - 14.0
  - 14.0
  - 14.0
  - 14.0
  - 14.0
  - 14.0
  - 14.0
  - 15.0
  - 15.0
  - 15.0
  - 15.0
  - 15.0
  - 15.0
  - 15.0
  - 15.0
  - 16.0
  - 16.0
  - 16.0
  - 16.0
  - 16.0
  - 16.0
  - 16.0
  - 16.0
  - 16.0
  - 17.0
  - 17.0
  - 17.0
  - 17.0
  - 17.0
  - 17.0
  - 17.0
  - 17.0
  - 17.0
  - 17.0
  - 18.0
  - 18.0
  - 18.0
  - 18.0
  - 18.0
  - 18.0
  - 18.0
  - 18.0
  - 18.0
  - 18.0
  - 19.0
  - 19.0
  - 19.0
  - 19.0
  - 19.0
  - 19.0
  - 19.0
  - 19.0
  - 19.0
  - 19.0
  - 19.0
  - 19.0
  - 20.0
  - 20.0
  - 20.0
  - 20.0
  - 20.0
  - 20.0
