nonlinear_morphing: yes
path_ct: '{subject$freesurfer_path}/../coregistration/CT_RAW.nii'
subject_code: yael_demo_001
path_mri: '{subject$freesurfer_path}/../coregistration/MRI_reference.nii'
project_name: YAEL
path_transform: '{subject$freesurfer_path}/../coregistration/CT_IJK_to_MR_RAS.txt'
transform_space: ijk2ras
localization_list: ${EXTDATA-SETTINGS|localization_list|json}
localization_plan: ${EXTDATA-SETTINGS|localization_plan|json}
