localization_plan: ${EXTDATA-SETTINGS|localization_plan|json}
localization_list: ${EXTDATA-SETTINGS|localization_list|json}
transform_space: ijk2ras
path_transform: '{subject$freesurfer_path}/../coregistration/CT_IJK_to_MR_RAS.txt'
project_name: devel
path_mri: '{subject$freesurfer_path}/../coregistration/MRI_reference.nii.gz'
subject_code: YAH
path_ct: '{subject$freesurfer_path}/../coregistration/CT_RAW.nii.gz'
nonlinear_morphing: yes
