electrode_export_data_type: tensor
electrodes_to_export: ''
trials_to_export: Raw, Only trials used in grouping factors
times_to_export: Raw, All available times
frequencies_to_export: Collapsed, Analysis window(s) only
electrode_export_file_type: HDF5
trial_outliers_list: ~
time_censor:
  enabled: no
  window:
  - 0.0
  - 1.0
project_name: demo
subject_code: DemoSubject
loaded_electrodes: 13-16,24
epoch_choice: auditory_onset
epoch_choice__trial_starts: -2
epoch_choice__trial_ends: 4
reference_name: default
baseline_settings:
  window:
  - - -1.0
    - -0.5
  scope: Per frequency, trial, and electrode
  unit_of_analysis: '% Change Power'
analysis_electrodes: '16 '
first_condition_groupings:
  '1':
    label: Ao
    conditions:
    - last_a
    - drive_a
    - known_a
    - meant_a
  '2':
    label: ''
    conditions: []
  '3':
    label: AV
    conditions:
    - last_av
    - drive_av
    - known_av
    - meant_av
second_condition_groupings:
  '1':
    label: MouthLeading
    conditions:
    - drive_a
    - last_a
    - drive_av
    - last_av
  '2':
    label: VoiceLeading
    conditions:
    - known_a
    - meant_a
    - known_av
    - meant_av
enable_second_condition_groupings: no
enable_custom_ROI: no
custom_roi_type: Filter only
custom_roi_variable: none
custom_roi_groupings:
  '1':
    label: ''
    conditions: []
analysis_settings:
  '1':
    label: A
    event: Trial Onset
    time:
    - 0
    - 0.5
    frequency:
    - 78
    - 152
electrodes_to_export_roi_name: none
electrodes_to_export_roi_categories: ~
