electrodes_to_export_roi_categories: ~
electrodes_to_export_roi_name: none
analysis_settings:
  '1':
    label: A
    event: Trial Onset
    time:
    - 0
    - 1.8
    frequency:
    - 75
    - 149
custom_roi_groupings:
  '1':
    label: ''
    conditions: []
custom_roi_variable: none
custom_roi_type: Filter only
enable_custom_ROI: no
enable_second_condition_groupings: no
second_condition_groupings:
  '1':
    label: ''
    conditions: []
  '2':
    label: ''
    conditions: []
first_condition_groupings:
  '1':
    label: Ao
    conditions: drive_av
  '2':
    label: Vo
    conditions: drive_v
analysis_electrodes: '14'
baseline_settings:
  window:
  - - -1.01
    - -0.52
  scope: Per frequency, trial, and electrode
  unit_of_analysis: '% Change Power'
reference_name: default
epoch_choice__trial_ends: 4
epoch_choice__trial_starts: -2
epoch_choice: auditory_onset
loaded_electrodes: 13-16,24
subject_code: DemoSubject
project_name: demo
time_censor:
  enabled: no
  window:
  - 0.0
  - 1.0
trial_outliers_list: ~
electrode_export_file_type: HDF5
frequencies_to_export: Collapsed, Analysis window(s) only
times_to_export: Raw, All available times
trials_to_export: Raw, Only trials used in grouping factors
electrodes_to_export: ''
electrode_export_data_type: tensor
